# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/chad/vmshare/project/ece544/ip_repo/edit_tsl235r_v1_0.cache/wt [current_project]
set_property parent.project_path /home/chad/vmshare/project/ece544/ip_repo/edit_tsl235r_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  /home/chad/vmshare/project/ece544/ip_repo/tsl235r_1.0
  /home/chad/vmshare/project/ece544/ip_repo/myip2_1.0
  /home/chad/vmshare/project/ece544/ip_repo/myip_1.0
  /home/chad/vmshare/project/ece544/ip_repo/tsl235r_1.0
  /home/chad/vmshare/project/ece544/proj2/ip
} [current_project]
read_verilog -library xil_defaultlib {
  /home/chad/vmshare/project/ece544/ip_repo/tsl235r_1.0/hdl/tsl235r_v1_0_S00_AXI.v
  /home/chad/vmshare/project/ece544/ip_repo/tsl235r_1.0/hdl/tsl235r_v1_0.v
  /home/chad/vmshare/project/ece544/ip_repo/tsl235r_1.0/hdl/pulse_width_det.v
}
synth_design -top tsl235r_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef tsl235r_v1_0.dcp
catch { report_utilization -file tsl235r_v1_0_utilization_synth.rpt -pb tsl235r_v1_0_utilization_synth.pb }
